#  Finger info
links_info:

  # Base link 
  base:
    name: 'Base'
    link: 'base'

  # Index link
  index:
    name: 'Index'
    link: '0'
    offset: 0
    joint_min: 
      - -0.314
      - -1.047
      - -0.506
      - -0.366
    joint_max: 
      - 2.23
      - 1.047
      - 1.3 #change 1.885 to 1.3 for temporal fix collision due to tactile can collide with part
      - 1.0 #change 2.042 to 1.0 for temporal fix collision due to tactile can collide with part

  # Middle link
  middle:
    name: 'Middle'
    link: '4'
    offset: 4
    joint_min: 
      - -0.314
      - -1.047
      - -0.506
      - -0.366
    joint_max: 
      - 2.23
      - 1.047
      - 1.3 #change 1.885 to 1.3 for temporal fix collision due to tactile can collide with part
      - 1.0 #change 2.042 to 1.0 for temporal fix collision due to tactile can collide with part
  
  # Ring link
  ring:
    name: 'Ring'
    link: '8'
    offset: 8
    joint_min: 
      - -0.314
      - -1.047
      - -0.506
      - -0.366
    joint_max: 
      - 2.23
      - 1.047
      - 1.3 #change 1.885 to 1.3 for temporal fix collision due to tactile can collide with part
      - 1.0 #change 2.042 to 1.0 for temporal fix collision due to tactile can collide with part

  # Thumb link
  thumb:
    name: 'Thumb'
    link: '12'
    offset: 12
    joint_min: 
      - -0.349
      - -0.47
      - -1.20
      - -1.34
    joint_max: 
      - 2.094
      - 2.443
      - 1.90
      - 1.88