name: Simple Grasping

dataset_path: ${data_path}/filtered

complete_demos:
  - demonstration_1
  - demonstration_2
  - demonstration_3
  - demonstration_4
  - demonstration_5
  - demonstration_6
  - demonstration_7
  - demonstration_8
  - demonstration_9
  - demonstration_10
  - demonstration_11

train_demos:
  - demonstration_1
  - demonstration_2
  - demonstration_3
  - demonstration_4
  - demonstration_5
  - demonstration_6
  - demonstration_7
  - demonstration_8
  - demonstration_9

test_demos:
  - demonstration_10
  - demonstration_11


