defaults:
  - _self_
  - /dataset: simple_grasping/ssl
  - /encoder: resnet18
  - /image_parameters: template

arm_position: slide
selected_view: 1

run_store_path: deploy_runs/${model}

vinn:
  min_action_distance: 0.01

  data_path: ${task.dataset.dataset_path}
  demos_list: ${task.dataset.complete_demos}

  nn_buffer_limit: 20 #20

  encoder_weights_path: model_weights/BYOL - ResNet18 RGB Encoder - View 1 - Simple Grasping SSL_epoch_240.pt
  absolute_actions: ${absolute_actions}

bc:
  predictor:
    input_dim: 512
    output_dim: 23
    hidden_dims: [1024, 2024, 512, 512] 
    use_batchnorm: true

  #model_weights: model_weights/Behavior Cloning - ${encoder.name} - View ${selected_view} - Simple Grasping/Behavior Cloning - ${encoder.name} - View ${selected_view} - Simple Grasping_epoch_1200.pt
  model_weights: model_weights/Behavior Cloning - ResNet34 RGB Encoder - View 1 - Simple Grasping/Behavior Cloning - ResNet34 RGB Encoder - View 1 - Simple Grasping_epoch_6700.pt
  #model_weights: model_weights/BYOL - ResNet18 RGB Encoder - View 1 - Simple Grasping SSL/Behavior Cloning - ResNet18 RGB Encoder - View 1 - Simple Grasping_epoch_6400.pt