defaults:
  - _self_
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

# Recorded Demostration Number
demo_num: 1

# data paths
storage_path: 'expert_dataset/recorded_data/'

# Number of tactile sensor board
num_tactiles: 2

# Number of view images 
num_cams: 2

# State Offset
offset: 0