defaults:
  - _self_
  - image_parameters: template # Used just for crop sizes
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

# Data to extract from the pickle files
ssl_data: false
sample: true
tactiles: true
color_images: true
depth_images: false
states: true
actions: true

# extract depth data type
depth_data_types: [
  "image",
  "raw_data"
]

# extract tactile data type
tactile_data_types: [
  "image",
  "raw_data"
]
# raw_data, image
# new type must contain image for image type, as it use for deciding the target path

# extract state data type
state_data_types: [
  "arm_abs_joint",
  "hand_abs_joint",
  "arm_ee_pose",
  ]
# arm_abs_ee, arm_rel_ee, arm_abs_joint, arm_rel_joint
# hand_coords, hand_abs_joint, hand_rel_joint

# extract action data type
action_data_types: [
  "arm_cmd_abs_joint",
  "arm_ee_pose",
  "arm_abs_joint",
  "hand_cmd_abs_joint",
  "hand_abs_joint",
  ] 
# arm_abs_ee, arm_rel_ee, arm_abs_joint, arm_rel_joint
# hand_coords, hand_abs_joint, hand_rel_joint

# data paths
storage_path: 'expert_dataset/recorded_data/'
filter_path: 'expert_dataset/filtered_data/'
target_path: 'expert_dataset/extracted_data/'

# Number of view images 
num_cams: 2 #3

# Delta for extracting states
# If we don't want to filter the data by hand and arm distance, we can set
# the hand_min_action_distance and arm_min_action_distance to 0 in
# configs/demo_extract.yaml.
hand_min_action_distance: 0 # cm
arm_min_action_distance: 0 # cm

hand_distance_unit: cm
arm_distance_unit: cm


