robot_cam_serial_numbers:
  # - "211422061450"         # 435i
  # - "207222071050"
  # - "207122078785"
  # - "f1230963"             # L515 -> must donwload pyrealsense2 2.54.2.xxxx
  - "311322301369"           # L455 -> hongwei's setup


# Robot camera stream resolution
resolution: [1280, 720]

# Visualize image streams
visualize_stream: True