robot_cam_serial_numbers:
  # - "211422061450"         # 435i
  # - "207222071050"
  - "f1230963"           # L515 -> must donwload pyrealsense2 2.54.2.xxxx
# Robot camera stream resolution


resolution: [1280, 720]

# Visualize image streams
visualize_stream: True