defaults:
  - _self_
  - robot_camera
  - tactile: null # paxini
  - tracker: dummy # pico # hamer 
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

finger_configs:
  freeze_index: false # Keep index finger fixed at [0, 0, 0, 0]
  freeze_middle: false # Keep middle finger fixed at [0, 0, 0, 0]
  three_dim: true
simulator: null
gripper: ctek # panda, null
gripper_init_state: open # close
arm: franka
hand: null # TODO
hydra:  
  output_subdir: null  
  run:  
    dir: .