retargeting:
  type: position
  urdf_path: schunk_hand/schunk_svh_hand_right.urdf
  wrist_link_name: "right_hand_base_link"

  target_joint_names: null
  target_link_names: [ "right_hand_c", "right_hand_t", "right_hand_s", "right_hand_r",
                        "right_hand_q", "right_hand_b", "right_hand_p", "right_hand_o", "right_hand_n", "right_hand_i"]

  target_link_human_indices: [ 4, 8, 12, 16, 20, 2, 6, 10, 14, 18 ]

  # A smaller alpha means stronger filtering, i.e. more smooth but also larger latency
  # 1 means no filter while 0 means not moving
  low_pass_alpha: 1
